In [1]:
from visiomode_analysis import session
from scipy.stats import norm

In [2]:
path = "./test_data/example-gonogo-leverpush.json"
path2 = "./test_data/example-targetonly-leverpush.json"

df = session.get_trials(path)

In [3]:
df

,animal_id,session_date,protocol,environment,experiment,start_time,stop_time,cue_onset,response,response_time,...,correction,pos_x,pos_y,dist_x,dist_y,sdt_type,stim_id,stim_period,stim_contrast,stim_freq
0,MM229,2022-03-09,gonogo,unknown,109hrb21d,4.484679,13.484679,9.484679,NaN,NaN,...,False,NaN,NaN,NaN,NaN,correct_rejection,isoluminantgray,NaN,NaN,NaN
1,MM229,2022-03-09,gonogo,unknown,109hrb21d,14.991839,19.065675,NaN,unknown,4.072411,...,False,400.0,240.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2,MM229,2022-03-09,gonogo,unknown,109hrb21d,19.067179,25.196554,24.067179,unknown,1.128456,...,False,400.0,240.0,0.0,0.0,hit,movinggrating,30,1.0,1.0
3,MM229,2022-03-09,gonogo,unknown,109hrb21d,26.700473,35.700473,31.700473,NaN,NaN,...,False,NaN,NaN,NaN,NaN,correct_rejection,isoluminantgray,NaN,NaN,NaN
4,MM229,2022-03-09,gonogo,unknown,109hrb21d,37.206945,43.881072,42.206945,unknown,1.670673,...,False,400.0,240.0,0.0,0.0,hit,movinggrating,30,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,MM229,2022-03-09,gonogo,unknown,109hrb21d,1765.847014,1774.055825,1770.847014,unknown,3.207015,...,True,400.0,240.0,0.0,0.0,false_alarm,isoluminantgray,NaN,NaN,NaN
301,MM229,2022-03-09,gonogo,unknown,109hrb21d,1774.057461,1781.851167,1779.057461,unknown,2.791260,...,True,400.0,240.0,0.0,0.0,false_alarm,isoluminantgray,NaN,NaN,NaN
302,MM229,2022-03-09,gonogo,unknown,109hrb21d,1781.852839,1786.325765,NaN,unknown,4.472022,...,True,400.0,240.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
303,MM229,2022-03-09,gonogo,unknown,109hrb21d,1786.327744,1795.327744,1791.327744,NaN,NaN,...,True,NaN,NaN,NaN,NaN,correct_rejection,isoluminantgray,NaN,NaN,NaN
304,MM229,2022-03-09,gonogo,unknown,109hrb21d,1796.831960,1802.662695,1801.831960,unknown,0.828844,...,False,400.0,240.0,0.0,0.0,false_alarm,isoluminantgray,NaN,NaN,NaN

In [4]:
session.get_metadata(path)

{'animal_id': 'MM229',
 'experiment': '109hrb21d',
 'session_date': datetime.date(2022, 3, 9),
 'environment': 'unknown',
 'protocol': 'gonogo',
 'version': 'unknown',
 'duration': 30.0,
 'session_start_time': '2022-03-09T12:04:03.108928',
 'response_device': 'leverpush',
 'reward_profile': 'waterreward',
 'stimulus_duration': 4000.0,
 'iti': 5000.0,
 'corrections_enabled': 'true',
 'device': 'meso-2',
 'stimuli': {'target_id': 'movinggrating',
  'target_period': '30',
  'target_contrast': '1.0',
  'target_freq': '1.0',
  'distractor_id': 'isoluminantgray'},
 'notes': ''}

In [5]:
import json

metadata = json.load(open(path, "r"))

In [6]:
len(df[df.sdt_type == "false_alarm"])

81

In [7]:
df[(df.response.notnull()) & (df.outcome == "correct") & (df.correction == False)].outcome.count()

np.int64(49)

In [8]:
df[(df.response.notnull()) & (df.outcome == "incorrect") & (df.correction == False)].outcome.count()

np.int64(40)

In [9]:
session.summary(path)

{'animal_id': 'MM229',
 'session_date': datetime.date(2022, 3, 9),
 'protocol': 'gonogo',
 'environment': 'unknown',
 'experiment': '109hrb21d',
 'correct': 61,
 'correct_wc': 100,
 'incorrect': 40,
 'incorrect_wc': 81,
 'correction_trials': 41,
 'hits': 49,
 'hits_wc': 49,
 'false_alarms': 40,
 'false_alarms_wc': 81,
 'correct_rejections': 12,
 'correct_rejections_wc': 51,
 'misses': 0,
 'misses_wc': 0,
 'cued': 101,
 'cued_wc': 181,
 'precued': 124,
 'total': 305,
 'percentage_correct': 60.396039603960396,
 'percentage_correct_wc': 55.24861878453039,
 'cued_ratio': 0.8145161290322581,
 'correction_ratio': 1.025,
 'hit_rate': 0.99,
 'hit_rate_wc': 0.99,
 'fa_rate': 0.7641509433962265,
 'fa_rate_wc': 0.6127819548872181,
 'd_prime': 1.606629016515605,
 'd_prime_wc': 2.039770694891421,
 'bias': -1.5230333657830384,
 'bias_wc': -1.3064625265951302,
 'perseveration': 0.5061728395061729,
 'rt': 0.7579958438873291,
 'rt_wc': 0.7752770185470581,
 'rt_hits': 0.8411245346069336,
 'rt_hits_wc': 0.8411245346069336,
 'rt_false_alarms': 0.724478006362915,
 'rt_false_alarms_wc': 0.7548151016235352,
 'rt_iqr': 0.6941144466400146,
 'rt_iqr_wc': 0.8146393895149231}

In [10]:
session.summary(path2)

/Users/celefthe/Projects/visiomode_analysis/.venv/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/celefthe/Projects/visiomode_analysis/.venv/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/celefthe/Projects/visiomode_analysis/.venv/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/celefthe/Projects/visiomode_analysis/.venv/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

{'animal_id': 'MM229',
 'session_date': datetime.date(2022, 3, 1),
 'protocol': 'targetonly',
 'environment': 'unknown',
 'experiment': '109hrb21d',
 'correct': 166,
 'correct_wc': 166,
 'incorrect': 0,
 'incorrect_wc': 0,
 'correction_trials': 0,
 'hits': 166,
 'hits_wc': 166,
 'false_alarms': 0,
 'false_alarms_wc': 0,
 'correct_rejections': 0,
 'correct_rejections_wc': 0,
 'misses': 71,
 'misses_wc': 71,
 'cued': 237,
 'cued_wc': 237,
 'precued': 54,
 'total': 291,
 'percentage_correct': 70.042194092827,
 'percentage_correct_wc': 70.042194092827,
 'cued_ratio': 4.388888888888889,
 'correction_ratio': 0.0,
 'hit_rate': 0.6995798319327731,
 'hit_rate_wc': 0.6995798319327731,
 'fa_rate': 0.5,
 'fa_rate_wc': 0.5,
 'd_prime': 0.5231924482394528,
 'd_prime_wc': 0.5231924482394528,
 'bias': -0.2615962241197264,
 'bias_wc': -0.2615962241197264,
 'perseveration': 0.0,
 'rt': 3.505884289741516,
 'rt_wc': 3.505884289741516,
 'rt_hits': 3.505884289741516,
 'rt_hits_wc': 3.505884289741516,
 'rt_false_alarms': nan,
 'rt_false_alarms_wc': nan,
 'rt_iqr': 4.261228859424591,
 'rt_iqr_wc': 4.261228859424591}

In [11]:
session.get_trials(path)

,animal_id,session_date,protocol,environment,experiment,start_time,stop_time,cue_onset,response,response_time,...,correction,pos_x,pos_y,dist_x,dist_y,sdt_type,stim_id,stim_period,stim_contrast,stim_freq
0,MM229,2022-03-09,gonogo,unknown,109hrb21d,4.484679,13.484679,9.484679,NaN,NaN,...,False,NaN,NaN,NaN,NaN,correct_rejection,isoluminantgray,NaN,NaN,NaN
1,MM229,2022-03-09,gonogo,unknown,109hrb21d,14.991839,19.065675,NaN,unknown,4.072411,...,False,400.0,240.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2,MM229,2022-03-09,gonogo,unknown,109hrb21d,19.067179,25.196554,24.067179,unknown,1.128456,...,False,400.0,240.0,0.0,0.0,hit,movinggrating,30,1.0,1.0
3,MM229,2022-03-09,gonogo,unknown,109hrb21d,26.700473,35.700473,31.700473,NaN,NaN,...,False,NaN,NaN,NaN,NaN,correct_rejection,isoluminantgray,NaN,NaN,NaN
4,MM229,2022-03-09,gonogo,unknown,109hrb21d,37.206945,43.881072,42.206945,unknown,1.670673,...,False,400.0,240.0,0.0,0.0,hit,movinggrating,30,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,MM229,2022-03-09,gonogo,unknown,109hrb21d,1765.847014,1774.055825,1770.847014,unknown,3.207015,...,True,400.0,240.0,0.0,0.0,false_alarm,isoluminantgray,NaN,NaN,NaN
301,MM229,2022-03-09,gonogo,unknown,109hrb21d,1774.057461,1781.851167,1779.057461,unknown,2.791260,...,True,400.0,240.0,0.0,0.0,false_alarm,isoluminantgray,NaN,NaN,NaN
302,MM229,2022-03-09,gonogo,unknown,109hrb21d,1781.852839,1786.325765,NaN,unknown,4.472022,...,True,400.0,240.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
303,MM229,2022-03-09,gonogo,unknown,109hrb21d,1786.327744,1795.327744,1791.327744,NaN,NaN,...,True,NaN,NaN,NaN,NaN,correct_rejection,isoluminantgray,NaN,NaN,NaN
304,MM229,2022-03-09,gonogo,unknown,109hrb21d,1796.831960,1802.662695,1801.831960,unknown,0.828844,...,False,400.0,240.0,0.0,0.0,false_alarm,isoluminantgray,NaN,NaN,NaN

In [17]:
trials = session.get_trials(path)
trials[(trials.response.notnull()) & (trials.cue_onset.notnull())].response_time.values

array([1.12845564, 1.67067313, 0.75222349, 0.7189033 , 0.58157992,
       2.63856554, 1.02317667, 1.09140873, 0.9076066 , 0.58795977,
       1.98388386, 3.61881399, 3.61073375, 1.04348946, 0.65499592,
       0.45944071, 0.26327109, 1.28396535, 0.87741184, 0.49710107,
       0.56599116, 0.84596944, 0.84112453, 0.4502275 , 1.91021109,
       0.53104758, 0.70769119, 3.00024486, 0.74060893, 0.49157977,
       0.62760639, 0.50835109, 0.42487359, 0.82556057, 0.3984499 ,
       0.39205909, 0.7548151 , 2.94736958, 0.44928479, 0.44550776,
       0.48086047, 0.41519713, 3.11189342, 2.50167394, 1.25001621,
       1.90612602, 0.99718571, 0.58729029, 0.4282968 , 0.55701089,
       0.63315582, 3.36899853, 0.5712564 , 0.64555478, 0.09124446,
       0.84036136, 0.50356007, 0.59616613, 0.27872372, 1.51335716,
       1.34386039, 2.26025271, 0.52169633, 1.84859204, 0.65409708,
       0.53360224, 0.94292784, 1.02442169, 0.21108174, 1.5925734 ,
       0.94771004, 0.1555655 , 3.32345533, 0.65784979, 0.54014683,
       0.4714303 , 0.78326321, 0.84392142, 0.15697026, 0.49913096,
       0.54947042, 0.24266291, 0.75799584, 0.5250001 , 0.21599102,
       0.46551609, 0.71576905, 0.87470198, 0.66445208, 1.33302426,
       0.60051966, 1.68480587, 1.64150071, 0.4529109 , 0.29112673,
       3.2855885 , 1.86356854, 2.44906521, 3.3949523 , 1.99941421,
       0.76729083, 1.65594125, 0.72418523, 0.8692615 , 1.29176593,
       0.87070751, 1.11195922, 0.66701508, 0.96783257, 1.75673079,
       0.72477078, 0.73314214, 1.209373  , 1.91370678, 3.23936605,
       0.14834547, 0.0970118 , 1.24704385, 0.89157176, 0.27321911,
       1.85134625, 1.16960907, 0.51525855, 0.65883112, 0.91119289,
       1.44596767, 0.83379054, 3.20701528, 2.79126048, 0.82884383])

In [19]:
session.get_rts(path, "false_alarm")

array([0.75222349, 0.7189033 , 0.58157992, 2.63856554, 1.02317667,
       1.09140873, 0.9076066 , 0.58795977, 1.98388386, 3.61073375,
       1.04348946, 0.65499592, 0.49710107, 0.56599116, 1.91021109,
       0.53104758, 0.70769119, 3.00024486, 0.49157977, 0.39205909,
       0.7548151 , 2.94736958, 0.44928479, 0.41519713, 3.11189342,
       2.50167394, 1.25001621, 1.90612602, 0.99718571, 0.58729029,
       0.4282968 , 0.63315582, 3.36899853, 0.09124446, 0.50356007,
       0.59616613, 0.27872372, 1.51335716, 1.34386039, 2.26025271,
       0.52169633, 1.84859204, 0.65409708, 0.53360224, 0.94292784,
       0.94771004, 0.1555655 , 3.32345533, 0.65784979, 0.78326321,
       0.84392142, 0.15697026, 0.49913096, 0.54947042, 0.24266291,
       0.75799584, 0.21599102, 0.46551609, 0.66445208, 1.33302426,
       0.60051966, 1.64150071, 0.4529109 , 0.29112673, 3.2855885 ,
       1.86356854, 2.44906521, 3.3949523 , 1.99941421, 0.76729083,
       1.65594125, 0.72418523, 0.66701508, 0.72477078, 0.14834547,
       0.0970118 , 1.24704385, 0.83379054, 3.20701528, 2.79126048,
       0.82884383])