In [1]:
from visiomode_analysis import subject, session
import glob
import pandas as pd

In [2]:
session_files = glob.glob("../*trials.csv")

subject_sessions = []
for session_file in session_files:
    subject_sessions.append(session.summary(session_file))

subject_df = pd.DataFrame(subject_sessions)

/Users/celefthe/Projects/visiomode_analysis/.venv/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/celefthe/Projects/visiomode_analysis/.venv/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/celefthe/Projects/visiomode_analysis/.venv/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/celefthe/Projects/visiomode_analysis/.venv/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [3]:
subject_df = subject_df.sort_values("session_date").reset_index(drop=True)

In [4]:
subject_df["session_id"] = subject_df.index + 1

In [5]:
subject_df["task_session"] = subject_df.groupby(["animal_id", "protocol"], sort=False)["session_id"].rank(
    ascending=True
)

In [6]:
subject_df

,animal_id,session_date,protocol,environment,experiment,correct,correct_wc,incorrect,incorrect_wc,correction_trials,...,rt,rt_wc,rt_hits,rt_hits_wc,rt_false_alarms,rt_false_alarms_wc,rt_iqr,rt_iqr_wc,session_id,task_session
0,MM229,2022-03-01,targetonly,unknown,109hrb21d,166,166,0,0,0,...,3.505884,3.505884,3.505884,3.505884,NaN,NaN,4.261229,4.261229,1,1.0
1,MM229,2022-03-09,gonogo,unknown,109hrb21d,61,100,40,81,41,...,0.757996,0.775277,0.841125,0.841125,0.724478,0.754815,0.694114,0.814639,2,1.0

In [7]:
subject.collate_sessions("../")

['../sub-MM229_exp-109hrb21d_ses-20220309_behaviour-gonogo_trials.csv', '../sub-MM229_exp-109hrb21d_ses-20220301_behaviour-targetonly_trials.csv']

/Users/celefthe/Projects/visiomode_analysis/.venv/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/celefthe/Projects/visiomode_analysis/.venv/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/celefthe/Projects/visiomode_analysis/.venv/lib/python3.14/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/celefthe/Projects/visiomode_analysis/.venv/lib/python3.14/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

,animal_id,session_date,protocol,environment,experiment,correct,correct_wc,incorrect,incorrect_wc,correction_trials,...,rt,rt_wc,rt_hits,rt_hits_wc,rt_false_alarms,rt_false_alarms_wc,rt_iqr,rt_iqr_wc,session_id,task_session
0,MM229,2022-03-01,targetonly,unknown,109hrb21d,166,166,0,0,0,...,3.505884,3.505884,3.505884,3.505884,NaN,NaN,4.261229,4.261229,1,1.0
1,MM229,2022-03-09,gonogo,unknown,109hrb21d,61,100,40,81,41,...,0.757996,0.775277,0.841125,0.841125,0.724478,0.754815,0.694114,0.814639,2,1.0